insert into tantargyak(megnevezes) values ('Biológia-egészségtan');
insert into tantargyak(megnevezes) values ('Dráma és tánc');
insert into tantargyak(megnevezes) values ('Ének-zene');
insert into tantargyak(megnevezes) values ('Erkölcstan');
insert into tantargyak(megnevezes) values ('Erkölcstan/hittan');
insert into tantargyak(megnevezes) values ('Etika');
insert into tantargyak(megnevezes) values ('Filozófia');
insert into tantargyak(megnevezes) values ('Fizika');
insert into tantargyak(megnevezes) values ('Földrajz');
insert into tantargyak(megnevezes) values ('Hon- és népismeret');
insert into tantargyak(megnevezes) values ('Idegen nyelv');
insert into tantargyak(megnevezes) values ('Informatika');
insert into tantargyak(megnevezes) values ('Kémia');
insert into tantargyak(megnevezes) values ('Kommunikáció magyar nyelv és irodalom');
insert into tantargyak(megnevezes) values ('Környezetismeret');
insert into tantargyak(megnevezes) values ('Latin örökségünk');
insert into tantargyak(megnevezes) values ('Magyar nyelv és irodalom');
insert into tantargyak(megnevezes) values ('Angol');
insert into tantargyak(megnevezes) values ('Német');
insert into tantargyak(megnevezes) values ('Spanyol');
insert into tantargyak(megnevezes) values ('Olasz');
insert into tantargyak(megnevezes) values ('Dán');
insert into tantargyak(megnevezes) values ('Izlandi');
insert into tantargyak(megnevezes) values ('Matematika');
insert into tantargyak(megnevezes) values ('Mozgóképkultúra és médiaismeret');
insert into tantargyak(megnevezes) values ('Művészetek');
insert into tantargyak(megnevezes) values ('Osztályközösség-építés');
insert into tantargyak(megnevezes) values ('Szabadon választható tantárgyak');
insert into tantargyak(megnevezes) values ('Szakiskolák');
insert into tantargyak(megnevezes) values ('Szakközépiskolák');
insert into tantargyak(megnevezes) values ('Tánc és mozgás');
insert into tantargyak(megnevezes) values ('Társadalmi');
insert into tantargyak(megnevezes) values ('Társadalomismeret');
insert into tantargyak(megnevezes) values ('Technika');
insert into tantargyak(megnevezes) values ('Természetismeret');
insert into tantargyak(megnevezes) values ('Természettudományi gyakorlatok');
insert into tantargyak(megnevezes) values ('Testnevelés és sport');
insert into tantargyak(megnevezes) values ('Történelem');
insert into tantargyak(megnevezes) values ('Vizuális kultúra');
