use suli;
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Angol',8,69,5);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Német',19,71,8);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Spanyol',18,99,3);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Izlandi',20,89,2);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Olasz',12,96,5);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Dráma',10,97,8);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Természetjáró',6,100,6);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Kreatív',14,92,3);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Zongora',11,86,9);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Oboa',9,75,7);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Hegedű',17,85,8);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Trombita',20,72,6);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Cselló',8,95,4);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Tánc',15,101,9);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Foci',17,102,1);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Kosárlabda',15,87,1);
insert into szakkor(nev,max_letszam,tanar_azon,heti_oraszam) values('Kézilabda',19,88,6);
