use suli;
insert into sport(megnevezes) values('falmászás');
insert into sport(megnevezes) values('ligarögbi');
insert into sport(megnevezes) values('búvárkodás');
insert into sport(megnevezes) values('kézilabda');
insert into sport(megnevezes) values('amerikai futball');
insert into sport(megnevezes) values('indiaca');
insert into sport(megnevezes) values('shinty');
insert into sport(megnevezes) values('backgammon');
insert into sport(megnevezes) values('biatlon');
insert into sport(megnevezes) values('darts');
insert into sport(megnevezes) values('galopp');
insert into sport(megnevezes) values('vízikosárlabda');
insert into sport(megnevezes) values('atlétika');
insert into sport(megnevezes) values('jégvitorlázás');
insert into sport(megnevezes) values('kajak-slalom');
insert into sport(megnevezes) values('rádióamatőr sportok');
insert into sport(megnevezes) values('hapkido');
insert into sport(megnevezes) values('labdarúgás');
insert into sport(megnevezes) values('kajak-kenu');
insert into sport(megnevezes) values('Galopp');
insert into sport(megnevezes) values('sítájfutás');
insert into sport(megnevezes) values('kick-box');
insert into sport(megnevezes) values('szinkronúszás');
insert into sport(megnevezes) values('kutyássportok');
insert into sport(megnevezes) values('traplövészet');
insert into sport(megnevezes) values('aerobik');
insert into sport(megnevezes) values('fives');
insert into sport(megnevezes) values('evezés');
insert into sport(megnevezes) values('súlyemelés');
insert into sport(megnevezes) values('síugrás');
