insert into sport(megnevezes) values('kézilabda');
insert into sport(megnevezes) values('racket ball');
insert into sport(megnevezes) values('pétanque');
insert into sport(megnevezes) values('jégkorong');
insert into sport(megnevezes) values('bowls lásd: golyósport');
insert into sport(megnevezes) values('gerelyhajítás');
insert into sport(megnevezes) values('kangoo jumps');
insert into sport(megnevezes) values('paintball');
insert into sport(megnevezes) values('repülőverseny');
insert into sport(megnevezes) values('biatlon');
insert into sport(megnevezes) values('ballonozás');
insert into sport(megnevezes) values('motokrossz');
insert into sport(megnevezes) values('ultramaraton');
insert into sport(megnevezes) values('motorkerékpársport');
insert into sport(megnevezes) values('szumó');
insert into sport(megnevezes) values('görkorcsolya');
insert into sport(megnevezes) values('ökölvívás');
insert into sport(megnevezes) values('alpinizmus');
insert into sport(megnevezes) values('krokett');
insert into sport(megnevezes) values('tájfutás');
insert into sport(megnevezes) values('superbike');
insert into sport(megnevezes) values('jégvitorlázás');
insert into sport(megnevezes) values('paintball');
insert into sport(megnevezes) values('jégtánc');
insert into sport(megnevezes) values('Galopp');
insert into sport(megnevezes) values('díjugratás');
insert into sport(megnevezes) values('trambulin (gumiasztal)-ugrás');
insert into sport(megnevezes) values('falmászás');
insert into sport(megnevezes) values('gyeplabda');
insert into sport(megnevezes) values('bowling');
insert into sport(megnevezes) values('többpróba');
insert into sport(megnevezes) values('tájékozódási túraverseny');
insert into sport(megnevezes) values('kanadai futball');
insert into sport(megnevezes) values('darts');
insert into sport(megnevezes) values('taekwondo');
insert into sport(megnevezes) values('íjászat ');
insert into sport(megnevezes) values('amerikai futball');
insert into sport(megnevezes) values('hármasugrás');
insert into sport(megnevezes) values('biatlon');
insert into sport(megnevezes) values('vitorlázórepülés');
insert into sport(megnevezes) values('racket ball');
insert into sport(megnevezes) values('szumó');
