insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Tehetségnap a diákok kreatív bemutatkozására.','2023-10-30',1524,21);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Könyvklub vagy olvasókör rendezvénye.','2024-01-24',1526,42);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Matematika- vagy tudományos verseny diákok között.','2024-12-25',1946,17);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Tavaszi fesztivál az iskola udvarán.','2024-11-03',1520,21);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Érettségi bál az évfolyam végén.','2023-08-26',1610,3);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Nemzeti ünnep megünneplése iskolai műsorral.','2023-11-20',1833,13);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Diákfilmfesztivál az iskolai filmprojektek bemutatására és díjazására.','2024-06-28',604,2);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Egészségnap az egészséges életmód népszerűsítésére.','2024-07-12',2070,33);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Szakmai előadások sorozata a különböző szakmákról és karrierlehetőségekről.','2024-05-22',632,7);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Farsangi felvonulás az iskola környékén.','2023-11-12',986,41);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Diákfórum az iskola jövőjéről.','2023-02-12',1067,11);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Tehetséges tanárok bemutatója és előadása.','2024-01-26',210,27);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Karnevál vagy jelmezes buli.','2023-12-10',2248,31);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Szülői-együttlét este: szülők és tanárok közös beszélgetése és találkozása.','2023-03-01',421,31);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Bűnmegelőzési nap a tanácsadás és a prevenció bemutatására.','2023-06-24',1571,36);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Sakk- vagy egyéb verseny a diák közösség számára.','2024-08-31',2199,41);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Diákzenei fesztivál.','2024-07-21',1797,21);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Könyvbemutató és olvasóköri esemény.','2023-11-22',552,35);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Karrierorientációs nap a pályaorientáció segítésére.','2024-07-11',1969,11);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Zenei előadás vagy koncert a helyi zenekarral vagy zenészekkel.','2024-04-05',625,36);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Sportnap az iskolai sportpályán.','2024-09-14',1402,23);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Önkéntes munkanap az iskola körül.','2024-08-23',109,16);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Filmklub vetítés a legújabb mozikból.','2024-10-08',755,32);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Diákkonferencia a közösségi problémák megvitatására.','2023-05-24',118,1);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Iskolai színházi előadás vagy színházi műhely foglalkozás.','2024-04-03',1477,21);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Zöld nap a fenntarthatóság és környezetvédelem jegyében.','2023-12-24',831,30);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Egészséges étel főzési verseny az egészséges táplálkozás ösztönzésére.','2023-12-10',867,31);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Bemutató nap a szakköri foglalkozásokról.','2023-05-29',1224,22);
insert into rendezvenyek(megnevezes,datum,max_letszam,tanterem_azon) VALUES('Téli sportnap síeléshez vagy korcsolyázáshoz.','2024-11-01',33,22);
