insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,783,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,804,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,1010,'Belépőjegyek értékesítése vagy ellenőrzése.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (5,790,'Ételek és italok készítése vagy kiszolgálása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (20,936,'Részvétel a műsorban vagy előadásokban.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (6,857,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (16,1095,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,1016,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,898,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,994,'Büfépult vagy étterem üzemeltetése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (16,975,'Parkolás irányítása és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (5,815,'Művészeti vagy kézműves foglalkozások vezetése.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,878,'Parkolás irányítása és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,936,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,893,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,866,'Részvétel a műsorban vagy előadásokban.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (21,783,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (10,892,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (21,858,'Rendezvényterem vagy helyszín előkészítése',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,1102,'Ételek és italok készítése vagy kiszolgálása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,1043,'Részvétel a műsorban vagy előadásokban.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (7,1022,'Támogatók és szponzorok kezelése és tájékoztatása.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,1033,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,959,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,881,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (26,882,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,885,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (23,900,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,874,'Vendégek tájékoztatása és segítése a helyszínen.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,1091,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,1009,'Környezet rendezése és díszítése az esemény előtt és alatt.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (26,988,'Utólagos takarítás és helyreállítás az esemény után.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,981,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,810,'Játékok vagy sportversenyek irányítása és pontozása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,853,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,898,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,849,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (7,877,'Információs pult vagy stand üzemeltetése.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (5,841,'Technikai eszközök és felszerelések kezelése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (16,812,'Részvétel a műsorban vagy előadásokban.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,833,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (16,1101,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,889,'Regisztráció és vendégfogadás.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,957,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,1000,'Művészeti vagy kézműves foglalkozások vezetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (20,837,'Játékok vagy tevékenységek vezetése a gyerekeknek.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,1107,'Belépőjegyek értékesítése vagy ellenőrzése.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (20,1046,'Belépőjegyek értékesítése vagy ellenőrzése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,797,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,1068,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (23,886,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,1110,'Regisztráció és vendégfogadás.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (16,833,'Technikai eszközök és felszerelések kezelése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,1102,'Vendégek tájékoztatása és segítése a helyszínen.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (12,1029,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,972,'Utólagos takarítás és helyreállítás az esemény után.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,821,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,1047,'Rendezvényterem vagy helyszín előkészítése',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,1060,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (21,1077,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,893,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (7,988,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,1063,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,918,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,1006,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,882,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (20,815,'Felhasználói visszajelzések gyűjtése az eseményről.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,1099,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,967,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,831,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,922,'Játékok vagy tevékenységek vezetése a gyerekeknek.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,1045,'Programfüzetek vagy információs anyagok készítése és terjesztése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,1005,'Utólagos takarítás és helyreállítás az esemény után.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,901,'Játékok vagy sportversenyek irányítása és pontozása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,873,'Technikai eszközök és felszerelések kezelése és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (10,857,'Utólagos takarítás és helyreállítás az esemény után.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,1043,'Játékok vagy tevékenységek vezetése a gyerekeknek.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,820,'Regisztráció és vendégfogadás.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (21,931,'Támogatók és szponzorok kezelése és tájékoztatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (10,966,'Játékok vagy sportversenyek irányítása és pontozása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (10,1102,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (13,901,'Felhasználói visszajelzések gyűjtése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (6,894,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (22,1028,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (13,956,'Programfüzetek vagy információs anyagok készítése és terjesztése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,828,'Regisztráció és vendégfogadás.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,863,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,869,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,865,'Részvétel a műsorban vagy előadásokban.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,1040,'Regisztráció és vendégfogadás.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,804,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,1050,'Környezet rendezése és díszítése az esemény előtt és alatt.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,827,'Felhasználói visszajelzések gyűjtése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (16,992,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,849,'Technikai eszközök és felszerelések kezelése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (23,1043,'Részvétel a műsorban vagy előadásokban.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (20,997,'Regisztráció és vendégfogadás.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,989,'Belépőjegyek értékesítése vagy ellenőrzése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (7,790,'Belépőjegyek értékesítése vagy ellenőrzése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (4,83,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (5,84,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (6,83,'Játékok vagy tevékenységek vezetése a gyerekeknek.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (3,95,'Felhasználói visszajelzések gyűjtése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (27,105,'Játékok vagy tevékenységek vezetése a gyerekeknek.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (17,114,'Büfépult vagy étterem üzemeltetése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (8,86,'Felhasználói visszajelzések gyűjtése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (6,134,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (29,120,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (5,69,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (16,76,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (3,69,'Játékok vagy sportversenyek irányítása és pontozása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (6,114,'Regisztráció és vendégfogadás.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,130,'Játékok vagy tevékenységek vezetése a gyerekeknek.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (23,119,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (29,107,'Rendezvényterem vagy helyszín előkészítése',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,71,'Játékok vagy sportversenyek irányítása és pontozása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,88,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (20,84,'Felhasználói visszajelzések gyűjtése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (8,81,'Büfépult vagy étterem üzemeltetése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (4,81,'Művészeti vagy kézműves foglalkozások vezetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (24,102,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (27,120,'Programfüzetek vagy információs anyagok készítése és terjesztése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (8,117,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (16,111,'Ételek és italok készítése vagy kiszolgálása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,131,'Jótékonysági adományok gyűjtése és kezelése.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (27,92,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (28,83,'Büfépult vagy étterem üzemeltetése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (15,124,'Környezet rendezése és díszítése az esemény előtt és alatt.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (2,118,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,110,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (4,86,'Művészeti vagy kézműves foglalkozások vezetése.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,126,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,112,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (24,74,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (14,83,'Környezet rendezése és díszítése az esemény előtt és alatt.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,76,'Vendégek tájékoztatása és segítése a helyszínen.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (3,132,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,136,'Környezet rendezése és díszítése az esemény előtt és alatt.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (6,124,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (16,125,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,131,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (20,72,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (3,97,'Rendezvényterem vagy helyszín előkészítése',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (4,112,'Technikai eszközök és felszerelések kezelése és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (21,106,'Regisztráció és vendégfogadás.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,127,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (23,72,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (26,99,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,92,'Ételek és italok készítése vagy kiszolgálása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (15,108,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (13,118,'Játékok vagy sportversenyek irányítása és pontozása.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (8,122,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (10,87,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (15,69,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (28,116,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (29,111,'Parkolás irányítása és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,83,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (10,130,'Vendégek tájékoztatása és segítése a helyszínen.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,134,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (15,79,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (4,74,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (20,85,'Felhasználói visszajelzések gyűjtése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (17,80,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,72,'Regisztráció és vendégfogadás.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (11,109,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (23,124,'Technikai eszközök és felszerelések kezelése és felügyelete.',True);
