use suli;
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (22,993,'Büfépult vagy étterem üzemeltetése és kezelése.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,854,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,1045,'Programfüzetek vagy információs anyagok készítése és terjesztése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,1075,'Részvétel a műsorban vagy előadásokban.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,996,'Belépőjegyek értékesítése vagy ellenőrzése.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,1070,'Ételek és italok készítése vagy kiszolgálása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,891,'Vendégek tájékoztatása és segítése a helyszínen.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,1010,'Részvétel a műsorban vagy előadásokban.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (9,927,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,1057,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (20,944,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (16,1032,'Regisztráció és vendégfogadás.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,935,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (22,900,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (12,957,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,1061,'Művészeti vagy kézműves foglalkozások vezetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (5,831,'Rendezvényterem vagy helyszín előkészítése',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,903,'Regisztráció és vendégfogadás.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,910,'Belépőjegyek értékesítése vagy ellenőrzése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,922,'Támogatók és szponzorok kezelése és tájékoztatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,1095,'Ételek és italok készítése vagy kiszolgálása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (12,915,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,1060,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (7,1061,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (16,902,'Ételek és italok készítése vagy kiszolgálása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,840,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,1037,'Programfüzetek vagy információs anyagok készítése és terjesztése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (23,992,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (6,819,'Környezet rendezése és díszítése az esemény előtt és alatt.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,972,'Büfépult vagy étterem üzemeltetése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (5,783,'Felhasználói visszajelzések gyűjtése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,839,'Ételek és italok készítése vagy kiszolgálása.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,983,'Művészeti vagy kézműves foglalkozások vezetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (7,784,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,845,'Rendezvényterem vagy helyszín előkészítése',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,836,'Támogatók és szponzorok kezelése és tájékoztatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (9,1074,'Játékok vagy sportversenyek irányítása és pontozása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,972,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,822,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (22,928,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (10,1072,'Vendégek tájékoztatása és segítése a helyszínen.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,804,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,965,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (16,855,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (23,1028,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,1004,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (5,982,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,829,'Büfépult vagy étterem üzemeltetése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (10,797,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (22,1102,'Környezet rendezése és díszítése az esemény előtt és alatt.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (5,963,'Művészeti vagy kézműves foglalkozások vezetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,940,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,812,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,1003,'Regisztráció és vendégfogadás.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,990,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,884,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,937,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (10,1082,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,1026,'Regisztráció és vendégfogadás.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,1013,'Vendégek tájékoztatása és segítése a helyszínen.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (26,913,'Fotó- és videófelvételek készítése az eseményről.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,1037,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,986,'Játékok vagy sportversenyek irányítása és pontozása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,1107,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,892,'Regisztráció és vendégfogadás.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,975,'Művészeti vagy kézműves foglalkozások vezetése.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,1051,'Művészeti vagy kézműves foglalkozások vezetése.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,1020,'Közösségi média tartalmak készítése és megosztása az eseményről.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,906,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,782,'Közösségi média tartalmak készítése és megosztása az eseményről.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (13,904,'Környezet rendezése és díszítése az esemény előtt és alatt.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (5,819,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,900,'Játékok vagy tevékenységek vezetése a gyerekeknek.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,797,'Programfüzetek vagy információs anyagok készítése és terjesztése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,1075,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,815,'Környezet rendezése és díszítése az esemény előtt és alatt.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,1097,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (26,810,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (12,950,'Közösségi média tartalmak készítése és megosztása az eseményről.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,899,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,808,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,989,'Belépőjegyek értékesítése vagy ellenőrzése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,1048,'Rendezvényterem vagy helyszín előkészítése',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,950,'Rendezvényterem vagy helyszín előkészítése',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,821,'Támogatók és szponzorok kezelése és tájékoztatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (6,1084,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,872,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,1087,'Programfüzetek vagy információs anyagok készítése és terjesztése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,891,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,863,'Jótékonysági adományok gyűjtése és kezelése.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (7,837,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,967,'Részvétel a műsorban vagy előadásokban.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,987,'Játékok vagy sportversenyek irányítása és pontozása.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,1075,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,993,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (21,1029,'Programfüzetek vagy információs anyagok készítése és terjesztése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,1047,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,834,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,1052,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,25,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (24,49,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,33,'Játékok vagy tevékenységek vezetése a gyerekeknek.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (29,28,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (29,67,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,47,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (29,33,'Játékok vagy tevékenységek vezetése a gyerekeknek.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (24,44,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,8,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (23,46,'Játékok vagy sportversenyek irányítása és pontozása.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (15,56,'Művészeti vagy kézműves foglalkozások vezetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,44,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (27,38,'Jótékonysági adományok gyűjtése és kezelése.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,24,'Vendégek tájékoztatása és segítése a helyszínen.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (5,49,'Felhasználói visszajelzések gyűjtése az eseményről.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,21,'Közösségi média tartalmak készítése és megosztása az eseményről.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (16,58,'Büfépult vagy étterem üzemeltetése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (27,32,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (11,26,'Részvétel a műsorban vagy előadásokban.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (2,53,'Támogatók és szponzorok kezelése és tájékoztatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (25,53,'Felhasználói visszajelzések gyűjtése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,55,'Támogatók és szponzorok kezelése és tájékoztatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (19,37,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,34,'Ételek és italok készítése vagy kiszolgálása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,37,'Belépőjegyek értékesítése vagy ellenőrzése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (25,37,'Rendezvényterem vagy helyszín előkészítése',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (17,49,'Regisztráció és vendégfogadás.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (29,44,'Technikai eszközök és felszerelések kezelése és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (21,6,'Büfépult vagy étterem üzemeltetése és kezelése.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (5,44,'Információs pult vagy stand üzemeltetése.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (21,61,'Játékok vagy sportversenyek irányítása és pontozása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,59,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (6,59,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,67,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,55,'Információs pult vagy stand üzemeltetése.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (26,35,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (10,34,'Parkolás irányítása és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,41,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (27,1,'Közösségi média tartalmak készítése és megosztása az eseményről.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (26,46,'Belépőjegyek értékesítése vagy ellenőrzése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,54,'Közösségi média tartalmak készítése és megosztása az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,31,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,26,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,13,'Utólagos takarítás és helyreállítás az esemény után.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (14,1,'Parkolás irányítása és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (28,41,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (8,28,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (5,27,'Fotó- és videófelvételek készítése az eseményről.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,41,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (4,36,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (19,41,'Környezet rendezése és díszítése az esemény előtt és alatt.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (1,41,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (21,59,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (2,56,'Támogatók és szponzorok kezelése és tájékoztatása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (23,27,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (26,14,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,50,'Szükséges felszerelések és eszközök biztosítása az eseményhez.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (17,15,'Felhasználói visszajelzések gyűjtése az eseményről.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (10,9,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (15,45,'Részvétel a műsorban vagy előadásokban.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (11,44,'Információs pult vagy stand üzemeltetése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (25,43,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.',True);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (23,20,'Jótékonysági adományok gyűjtése és kezelése.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (3,57,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (24,39,'Technikai eszközök és felszerelések kezelése és felügyelete.',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (13,62,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők',False);
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,59,'Bemutatók vagy demonstrációk előkészítése és bemutatása.',False);
