insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,940,'Támogatók és szponzorok kezelése és tájékoztatása.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (9,1105,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,1053,'Ételek és italok készítése vagy kiszolgálása.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,933,'Belépőjegyek értékesítése vagy ellenőrzése.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,873,'Információs pult vagy stand üzemeltetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (9,1105,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,983,'Művészeti vagy kézműves foglalkozások vezetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (5,1085,'Regisztráció és vendégfogadás.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,795,'Regisztráció és vendégfogadás.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (12,1069,'Információs pult vagy stand üzemeltetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,963,'Támogatók és szponzorok kezelése és tájékoztatása.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,1029,'Közösségi média tartalmak készítése és megosztása az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,874,'Rendezvényterem vagy helyszín előkészítése','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,825,'Információs pult vagy stand üzemeltetése.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,824,'Jótékonysági adományok gyűjtése és kezelése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (12,1046,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,945,'Támogatók és szponzorok kezelése és tájékoztatása.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (12,936,'Jótékonysági adományok gyűjtése és kezelése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,829,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,851,'Szükséges felszerelések és eszközök biztosítása az eseményhez.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,1017,'Parkolás irányítása és felügyelete.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,1001,'Szükséges felszerelések és eszközök biztosítása az eseményhez.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,888,'Rendezvényterem vagy helyszín előkészítése','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,903,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (9,966,'Rendezvényterem vagy helyszín előkészítése','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (21,980,'Játékok vagy sportversenyek irányítása és pontozása.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,996,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (9,1022,'Művészeti vagy kézműves foglalkozások vezetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (17,790,'Közösségi média tartalmak készítése és megosztása az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (10,804,'Közösségi média tartalmak készítése és megosztása az eseményről.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,877,'Közösségi média tartalmak készítése és megosztása az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (7,782,'Közösségi média tartalmak készítése és megosztása az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,1037,'Szükséges felszerelések és eszközök biztosítása az eseményhez.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (9,816,'Belépőjegyek értékesítése vagy ellenőrzése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,918,'Közösségi média tartalmak készítése és megosztása az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,857,'Információs pult vagy stand üzemeltetése.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,1108,'Szükséges felszerelések és eszközök biztosítása az eseményhez.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (6,791,'Részvétel a műsorban vagy előadásokban.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,1037,'Bemutatók vagy demonstrációk előkészítése és bemutatása.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,990,'Információs pult vagy stand üzemeltetése.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,837,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,1073,'Fotó- és videófelvételek készítése az eseményről.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,800,'Parkolás irányítása és felügyelete.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (20,813,'Vendégek tájékoztatása és segítése a helyszínen.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,880,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,1077,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (8,847,'Programfüzetek vagy információs anyagok készítése és terjesztése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,1042,'Támogatók és szponzorok kezelése és tájékoztatása.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,793,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,1048,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,1029,'Támogatók és szponzorok kezelése és tájékoztatása.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (6,851,'Információs pult vagy stand üzemeltetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,863,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (23,868,'Belépőjegyek értékesítése vagy ellenőrzése.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,910,'Rendezvényterem vagy helyszín előkészítése','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,853,'Játékok vagy tevékenységek vezetése a gyerekeknek.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,836,'Játékok vagy sportversenyek irányítása és pontozása.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (4,844,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (28,1097,'Támogatók és szponzorok kezelése és tájékoztatása.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (9,805,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,873,'Ételek és italok készítése vagy kiszolgálása.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,1024,'Programfüzetek vagy információs anyagok készítése és terjesztése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (6,805,'Játékok vagy tevékenységek vezetése a gyerekeknek.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,987,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (14,995,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (3,823,'Rendezvényterem vagy helyszín előkészítése','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (21,1110,'Utólagos takarítás és helyreállítás az esemény után.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,1002,'Művészeti vagy kézműves foglalkozások vezetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,863,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,852,'Büfépult vagy étterem üzemeltetése és kezelése.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,827,'Támogatók és szponzorok kezelése és tájékoztatása.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,992,'Szükséges felszerelések és eszközök biztosítása az eseményhez.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (24,994,'Jótékonysági adományok gyűjtése és kezelése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,876,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (27,957,'Fotó- és videófelvételek készítése az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,940,'Felhasználói visszajelzések gyűjtése az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (26,1067,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (1,855,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (19,966,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,1104,'Technikai eszközök és felszerelések kezelése és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (9,1001,'Parkolás irányítása és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (13,880,'Közösségi média tartalmak készítése és megosztása az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,799,'Rendezvényterem vagy helyszín előkészítése','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,850,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,1055,'Részvétel a műsorban vagy előadásokban.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (21,922,'Utólagos takarítás és helyreállítás az esemény után.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,824,'Utólagos takarítás és helyreállítás az esemény után.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (25,953,'Belépőjegyek értékesítése vagy ellenőrzése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (26,979,'Művészeti vagy kézműves foglalkozások vezetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (13,813,'Parkolás irányítása és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (21,947,'Játékok vagy sportversenyek irányítása és pontozása.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (18,1026,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (23,928,'Jótékonysági adományok gyűjtése és kezelése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (6,1034,'Fotó- és videófelvételek készítése az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (29,906,'Programfüzetek vagy információs anyagok készítése és terjesztése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (15,917,'Büfépult vagy étterem üzemeltetése és kezelése.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (2,916,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.','False');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (11,1056,'Ételek és italok készítése vagy kiszolgálása.','True');
insert into rendezveny_szervezok(rendezveny_azon,diak_azon,feladat,jutalom) values (12,933,'Programfüzetek vagy információs anyagok készítése és terjesztése.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (28,117,'Ételek és italok készítése vagy kiszolgálása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (11,116,'Felhasználói visszajelzések gyűjtése az eseményről.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,134,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (15,108,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (3,87,'Belépőjegyek értékesítése vagy ellenőrzése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (14,88,'Közösségi média tartalmak készítése és megosztása az eseményről.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (2,101,'Ételek és italok készítése vagy kiszolgálása.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (1,89,'Részvétel a műsorban vagy előadásokban.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,136,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (24,84,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,73,'Büfépult vagy étterem üzemeltetése és kezelése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (20,106,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (1,93,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (20,120,'Támogatók és szponzorok kezelése és tájékoztatása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (11,110,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (17,73,'Szükséges felszerelések és eszközök biztosítása az eseményhez.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (13,134,'Fotó- és videófelvételek készítése az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (27,130,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (24,128,'Felhasználói visszajelzések gyűjtése az eseményről.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (3,117,'Ételek és italok készítése vagy kiszolgálása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (8,117,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (14,96,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (1,105,'Játékok vagy sportversenyek irányítása és pontozása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (4,81,'Szakmai előadások vagy műhelyek megszervezése és lebonyolítása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (6,99,'Részvétel a műsorban vagy előadásokban.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,128,'Technikai eszközök és felszerelések kezelése és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (24,100,'Művészeti vagy kézműves foglalkozások vezetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,129,'Vendégek tájékoztatása és segítése a helyszínen.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (1,103,'Gyerekek vagy diákok felügyelete és segítése különböző tevékenységek során.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (17,99,'Felhasználói visszajelzések gyűjtése az eseményről.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (4,126,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,97,'Szükséges felszerelések és eszközök biztosítása az eseményhez.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (13,88,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (5,104,'Fogyóeszközök nyomon követése és újratöltése (pl. papírtörlők','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (29,111,'Részvétel a műsorban vagy előadásokban.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (5,91,'Technikai eszközök és felszerelések kezelése és felügyelete.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,133,'Játékok vagy sportversenyek irányítása és pontozása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (5,92,'Környezet rendezése és díszítése az esemény előtt és alatt.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (11,136,'Információs pult vagy stand üzemeltetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (3,105,'Büfépult vagy étterem üzemeltetése és kezelése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (5,108,'Közösségi média tartalmak készítése és megosztása az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (13,78,'Információs pult vagy stand üzemeltetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,123,'Versenyek vagy vetélkedők lebonyolítása és felügyelete.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,101,'Fotó- és videófelvételek készítése az eseményről.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (7,130,'Rendezvényterem vagy helyszín előkészítése','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,87,'Művészeti vagy kézműves foglalkozások vezetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (24,86,'Belépőjegyek értékesítése vagy ellenőrzése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (11,104,'Bemutatók vagy demonstrációk előkészítése és bemutatása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (8,98,'Ételek és italok készítése vagy kiszolgálása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (23,118,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (29,124,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,112,'Művészeti vagy kézműves foglalkozások vezetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (21,127,'Fotó- és videófelvételek készítése az eseményről.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (14,106,'Ételek és italok készítése vagy kiszolgálása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,86,'Művészeti vagy kézműves foglalkozások vezetése.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (12,102,'Díjak vagy ajándékok kiosztása a versenyek vagy vetélkedők győzteseinek.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (4,79,'Játékok vagy sportversenyek irányítása és pontozása.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (18,133,'Tűz- és biztonsági ellenőrzések végzése és felügyelete.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (6,129,'Vendégek tájékoztatása és segítése a helyszínen.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (26,72,'Művészeti vagy kézműves foglalkozások vezetése.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (21,71,'Játékok vagy tevékenységek vezetése a gyerekeknek.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (22,107,'Játékok vagy tevékenységek vezetése a gyerekeknek.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (13,125,'Művészeti vagy kézműves foglalkozások vezetése.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (9,124,'Művészeti vagy kézműves foglalkozások vezetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (10,129,'Információs pult vagy stand üzemeltetése.','False');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (25,73,'Szükséges felszerelések és eszközök biztosítása az eseményhez.','True');
insert into rendezveny_szervezok(rendezveny_azon,tanar_azon,feladat,jutalom) values (16,135,'Hangosítás és technikai támogatás biztosítása az előadásokhoz és műsorokhoz.','True');
