insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(607,'2023-07-19','Igazgatói','A gyerek ellenőrző könyve negyedik éve nincs aláírva. Kedves Szülő; nem tud írni?');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(526,'2023-05-27','Igazgatói','T. Szülő! Leánya irodalomórán vihogott. ');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(985,'2023-02-05','Osztályfőnöki','Figyelmeztetés után is rágja a földgömböt a gyerek. Újból figyelmeztetem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(616,'2023-01-06','Osztályfőnöki','Szellemessége és feltűnési viszketegsége a pofátlanság határait súrolja.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(695,'2023-04-23','Szaktanári','Fia óra alatt a pad sarkával jéghokisat játszott a terem körül; eközben MÁV bemondásokat tartott; melyben a rólam elnevezett szerelvény közeledtére figyelmeztetett');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(987,'2023-06-19','Igazgatói','Gyermekük súlyosan sértő magatartást tanúsított a csontvázzal szemben. Ráadásul elnevezte Bélának.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(851,'2023-12-21','Igazgatói','Az osztályfőnöki dicséretet még mindig nem íratta alá. Megintem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(865,'2023-08-10','Szaktanári','A gyerek ellenőrző könyve negyedik éve nincs aláírva. Kedves Szülő; nem tud írni?');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(792,'2023-11-20','Igazgatói','Fiuk a szomszédja uzsonnáját a legnagyobb titokban befalta.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(773,'2023-12-08','Osztályfőnöki','Tisztelt Szülők! Karcsika ma fogalmazás órán felváltva bőgött; sípolt és fújtatott. Állítása szerint marhavagont játszott.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(929,'2023-01-22','Igazgatói','az óra elején bebújt a szekrénybe; és onnan többszöri felszólításra sem jött elő. Kérem beszéljen vele!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1022,'2023-06-25','Szaktanári','Lacinak két ellenőrzője van. Én mosom kezeimet. – Osztályfőnök.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(757,'2023-11-20','Osztályfőnöki','Gyermeke a tanóra alatt; a padokon lévő kiflimorzsákat eszegette');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(768,'2023-03-05','Osztályfőnöki','Az osztályfőnöki dicséretet még mindig nem íratta alá. Megintem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(848,'2023-07-09','Szaktanári','Jancsika rendszeresen nem issza meg az iskolatejet.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(871,'2023-06-25','Szaktanári','T. Szülő! Leánya irodalomórán vihogott. ');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(520,'2023-05-12','Osztályfőnöki','Figyelmeztetés után is rágja a földgömböt a gyerek. Újból figyelmeztetem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(643,'2023-06-15','Igazgatói','A gyerek a szünetben az iskola keretein kívül játszott.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(494,'2023-08-03','Osztályfőnöki','A fia a házi feladatát rendszeresen a társairól másolja át! Mi lesz Így belőle?');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(934,'2023-07-31','Igazgatói','Tisztelt Szülők! Karcsika ma fogalmazás órán felváltva bőgött; sípolt és fújtatott. Állítása szerint marhavagont játszott.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(807,'2023-06-15','Szaktanári','T. Szülő; a gyereke állandóan tőlem kér tollat. Lássa el otthon írószerrel.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(804,'2023-09-30','Osztályfőnöki','Katika nem tud olvasni!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1085,'2023-10-15','Osztályfőnöki','Kesztyűben ül az órán; mert fázik a keze és nem írja a szavakat.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(652,'2023-10-08','Osztályfőnöki','Gyermekük súlyosan sértő magatartást tanúsított a csontvázzal szemben. Ráadásul elnevezte Bélának.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(763,'2023-11-18','Igazgatói','Körzőjével veszélyeztette társai testi épségét');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(622,'2023-07-21','Igazgatói','Figyelmeztetés után is rágja a földgömböt a gyerek. Újból figyelmeztetem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(926,'2023-05-24','Szaktanári','az óra elején bebújt a szekrénybe; és onnan többszöri felszólításra sem jött elő. Kérem beszéljen vele!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(977,'2023-01-26','Igazgatói','Értesítem a T. Szülőket; hogy fiuk történelemkönyve lapokból áll.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1089,'2023-11-19','Igazgatói','Fiuk a szomszédja uzsonnáját a legnagyobb titokban befalta.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(688,'2023-02-23','Szaktanári','T. Szülő; fia órán neveletlenül beszélt. Figyelmeztetem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(645,'2023-05-31','Szaktanári','Gyermekük nem íratta alá az osztályfőnöki dicséretet. Intőt kap.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(805,'2023-12-08','Osztályfőnöki','Gyermeke az órámon írószer nélkül akart írni.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(870,'2023-04-11','Igazgatói','Gyermekük óra alatt orvul elfogyasztotta padtársa uzsonnáját.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(958,'2023-03-12','Szaktanári','Szellemessége és feltűnési viszketegsége a pofátlanság határait súrolja.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(755,'2023-06-30','Osztályfőnöki','Kedves Anyuka! Kisfia ma a folyosón laposkúszásban közlekedett; a kabátok közé rejtőzött; és bukfencezve haladt előre egyik oldalról a másikra; miközben titkos üzeneteket ordított a markában tartott tolltartójába arról; hogy jövök.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(509,'2023-01-23','Szaktanári','A gyerek a szünetben az iskola keretein kívül játszott.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(736,'2023-10-01','Osztályfőnöki','T. Szülő; fia órán neveletlenül beszélt. Figyelmeztetem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(552,'2023-04-10','Igazgatói','Gyermeke azt mondta; hogy szerinte jó gondolat lenne az egyik osztálytársát bántalmazni; ezért figyelmeztetem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(743,'2023-08-04','Szaktanári','Tájékoztatom; hogy gyerekének egy ideje átható kénszaga van.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(501,'2023-08-10','Igazgatói','T. Szülő; a gyereke állandóan tőlem kér tollat. Lássa el otthon írószerrel.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(988,'2023-06-08','Osztályfőnöki','Kémia órán a kísérleti anyagot elfogyasztotta.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(895,'2023-01-10','Osztályfőnöki','Óra alatt kukorékolt!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(669,'2023-09-25','Igazgatói','T. Szülő; a gyereke állandóan tőlem kér tollat. Lássa el otthon írószerrel.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(860,'2023-05-19','Osztályfőnöki','Elkobozta társa tízóraiját');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(925,'2023-04-26','Igazgatói','Megkérném önöket; hogy ismertessék meg gyerekükkel kulturált vécéhasználat alapjait!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(760,'2023-08-18','Osztályfőnöki','Lacinak két ellenőrzője van. Én mosom kezeimet. – Osztályfőnök.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(727,'2023-08-10','Szaktanári','Nem elég; hogy a szünetekben állandóan krétacsatákat vív osztálytársaival; ráadásul mindig veszít.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1045,'2023-07-01','Osztályfőnöki','Nem elég; hogy a szünetekben állandóan krétacsatákat vív osztálytársaival; ráadásul mindig veszít.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(532,'2023-08-17','Osztályfőnöki','T. Szülő. Gyerekük rányitott vizelés közben az osztályfőnkre. Ezért igazgatói intőben részesítem!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(833,'2023-03-14','Igazgatói','Körzőjével veszélyeztette társai testi épségét');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(999,'2023-04-27','Igazgatói','Kedves Anyuka! Kisfia ma a folyosón laposkúszásban közlekedett; a kabátok közé rejtőzött; és bukfencezve haladt előre egyik oldalról a másikra; miközben titkos üzeneteket ordított a markában tartott tolltartójába arról; hogy jövök.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1095,'2023-04-13','Osztályfőnöki','Fiuk a szomszédja uzsonnáját a legnagyobb titokban befalta.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(817,'2023-09-30','Igazgatói','Az osztályfőnöki dicséretet még mindig nem íratta alá. Megintem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(796,'2023-06-12','Osztályfőnöki','Fia a szünetben sztrájkot szervezett. Letörtük.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1077,'2023-04-20','Szaktanári','Gyermekük matekórán a zsiráf hangját utánozta.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(829,'2023-02-19','Osztályfőnöki','Gyermeke azt mondta; hogy szerinte jó gondolat lenne az egyik osztálytársát bántalmazni; ezért figyelmeztetem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1062,'2023-01-26','Szaktanári','Kémiaóra folyamán padtársával zümmögött és brummogott.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(817,'2023-12-13','Igazgatói','Tisztelt Szülők! Karcsika ma fogalmazás órán felváltva bőgött; sípolt és fújtatott. Állítása szerint marhavagont játszott.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(953,'2023-02-27','Osztályfőnöki','Óra alatt kukorékolt!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(869,'2023-01-19','Igazgatói','Figyelmeztetés után is rágja a földgömböt a gyerek. Újból figyelmeztetem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1027,'2023-09-28','Igazgatói','Ne sz@rj az ülőkére; te hülye! Ez kulturált viselkedés???');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1024,'2023-02-12','Osztályfőnöki','Tisztelt szülők! Lányuk a szünetben az udvaron ugrált a pocsolyában a váltócipőben. Kérem ennek a tudomásul vételét!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(973,'2023-08-08','Szaktanári','Gyermeke az órámon írószer nélkül akart írni.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(787,'2023-06-10','Szaktanári','gyerekük rendetlenkedik az órákon! El fogom tanácsolni az iskolából! - Az iskola igazgatója.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(597,'2023-03-27','Osztályfőnöki','Fia az órán szőllőt (így!!!) evett…');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(503,'2023-01-14','Osztályfőnöki','Körzőjével veszélyeztette társai testi épségét');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1032,'2023-03-04','Szaktanári','Jelentés alatt-fiú létére- tehénbőgést hallatott. Rovót kap.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1015,'2023-11-27','Osztályfőnöki','A magyarórán háromszor szóltam rá; hogy ne bontsa a falat! Kérem fülészetre vinni!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(881,'2023-03-12','Szaktanári','Kedves Szülő; tájékoztatom; hogy Péter az étkezdében többször is kézzel evett evőeszköz helyett.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(543,'2023-12-25','Igazgatói','Gyermeke azt mondta; hogy szerinte jó gondolat lenne az egyik osztálytársát bántalmazni; ezért figyelmeztetem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(669,'2023-06-21','Osztályfőnöki','Tisztelt Szülők! Figyelmeztessék Klárikát; hogy a Csiga-biga gyere ki-t énekórán; alsó tagozatban énekelje; ne biológián; a puhatestűek tanulmányozása közben.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(714,'2023-12-04','Igazgatói','Kedves Szülők! Tisztelettel jelzem Önök felé; hogy Sanyika ma kutyaszaros cipővel trappolt végig a tantermen és minden összebarmolt.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(769,'2023-03-01','Osztályfőnöki','az óra elején bebújt a szekrénybe; és onnan többszöri felszólításra sem jött elő. Kérem beszéljen vele!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(990,'2023-10-24','Szaktanári','Gyermeke az órámon írószer nélkül akart írni.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(580,'2023-08-22','Osztályfőnöki','T. Szülő! Leánya irodalomórán vihogott. ');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(695,'2023-10-26','Igazgatói','Az Aranyköpések az iskolapadból megvolt már?!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(967,'2023-08-31','Osztályfőnöki','Kedves Szülők! Tisztelettel jelzem Önök felé; hogy Sanyika ma kutyaszaros cipővel trappolt végig a tantermen és minden összebarmolt.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(887,'2023-07-12','Szaktanári','T. Szülő! Leánya irodalomórán vihogott. ');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(637,'2023-03-15','Igazgatói','Értesítem a T. Szülőket; hogy fiuk történelemkönyve lapokból áll.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(711,'2023-10-23','Szaktanári','T. Szülő! Leánya irodalomórán vihogott. ');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(816,'2023-03-02','Osztályfőnöki','T. Szülő! Leánya irodalomórán vihogott. ');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(684,'2023-03-11','Szaktanári','Az osztályfőnöki dicséretet még mindig nem íratta alá. Megintem.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(813,'2023-01-07','Osztályfőnöki','Kémiaóra folyamán padtársával zümmögött és brummogott.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(770,'2023-10-21','Osztályfőnöki','A gyerek az órán beszél; és állandóan jelentkezik.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(704,'2023-06-17','Osztályfőnöki','T. Szülő. Gyerekük rányitott vizelés közben az osztályfőnkre. Ezért igazgatói intőben részesítem!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(718,'2023-03-28','Szaktanári','Gyermekük matekórán a zsiráf hangját utánozta.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(888,'2023-08-08','Szaktanári','Óra alatt kukorékolt!');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(1102,'2023-07-28','Szaktanári','Kedves Szülők! Tisztelettel jelzem Önök felé; hogy Sanyika ma kutyaszaros cipővel trappolt végig a tantermen és minden összebarmolt.');
insert into intok(diak_azon,datum,into_tipusa,into_szoveg) values(889,'2023-10-02','Osztályfőnöki','Gyermeke a tanóra alatt; a padokon lévő kiflimorzsákat eszegette');
